version: "3.4"
services:
  gray-matter-web:
    container_name: gray-matter-web
    restart: always
    build: .
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - nodeapp-network
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    command: "node --inspect=0.0.0.0:9229 ./server/server.js"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge